const products = [
  {
    _id: "1",
    name: "rouginaquite",
    description: "Ongle rouge avec une belle bouche endiablé",
    categories: "Ongle",
    price: "54,99",
    stocks: "100",
    image: "../images/ongle-1.jpg",
    rating: "4.5",
    numReview: "4",
  },
  {
    _id: "2",
    name: "Lidisma",
    description: "Ongle rouge avec sans belle bouche endiablé",
    categories: "Ongle",
    price: "44,99",
    stocks: "100",
    image: "../images/ongle-2.jpg",
    rating: "4",
    numReview: "15",
  },
  {
    _id: "3",
    name: "nièbè",
    description: "On va nièbe quand?",
    categories: "stuff",
    price: "540,99",
    stocks: "10",
    image: "../images/ongle-3.jpg",
    rating: "4.5",
    numReview: "48",
  },
  {
    _id: "4",
    name: "boobs",
    description: "blabla balbkla",
    categories: "Ongle",
    price: "54,99",
    stocks: "100",
    image: "../images/ongle-4.jpg",
    rating: "4.5",
    numReview: "150",
  },
  {
    _id: "5",
    name: "rouginaquite 2",
    description:
      "Ongle rouge avec une belle bouche endiablé/ non je ne crois pas",
    categories: "Ongle",
    price: "54,99",
    stocks: "100",
    image: "../images/ongle-5.jpg",
    rating: "4.5",
    numReview: "150",
  },
  {
    _id: "6",
    name: "rouginaquite 3",
    description:
      "Ongle rouge avec une belle bouche endiablé/ encore monsonge je suis fatigué",
    categories: "Ongle",
    price: "5,99",
    stocks: "0",
    image: "../images/ongle-6.jpg",
    rating: "4",
    numReview: "50",
  },
];

export default products;
